sudo: false

branches:
  only:
    - "master"
    - "develop"

language: ruby
cache: bundler

rvm:
  - "2.0.0"
  - "2.1.8"
  - "2.2.4"
  - "2.3.0"
  - "2.4.0"
  - "jruby-19mode"

gemfile:
  - "gemfiles/capistrano2.gemfile"
  - "gemfiles/capistrano3.gemfile"
  - "gemfiles/no_dependencies.gemfile"
  - "gemfiles/padrino.gemfile"
  - "gemfiles/rails-3.2.gemfile"
  - "gemfiles/rails-4.0.gemfile"
  - "gemfiles/rails-4.1.gemfile"
  - "gemfiles/rails-4.2.gemfile"
  - "gemfiles/rails-5.0.gemfile"
  - "gemfiles/rails-5.1.gemfile"
  - "gemfiles/resque.gemfile"
  - "gemfiles/sequel.gemfile"
  - "gemfiles/sequel-435.gemfile"
  - "gemfiles/sidekiq.gemfile"
  - "gemfiles/sinatra.gemfile"
  - "gemfiles/grape.gemfile"
  - "gemfiles/webmachine.gemfile"
  - "gemfiles/que.gemfile"

matrix:
  fast_finish: true
  include:
    - rvm: "2.3.0"
      gemfile: "gemfiles/no_dependencies.gemfile"
      script: "bundle exec rubocop"
  exclude:
    # We don't currently support jRuby
    - rvm: "jruby-19mode"

    # Rails 5 doesn't support Ruby < 2.2
    - rvm: "2.0.0"
      gemfile: "gemfiles/sidekiq.gemfile"
    - rvm: "2.1.8"
      gemfile: "gemfiles/sidekiq.gemfile"
    - rvm: "jruby-19mode"
      gemfile: "gemfiles/sidekiq.gemfile"
    - rvm: "2.0.0"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "2.1.8"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "2.0.0"
      gemfile: "gemfiles/rails-5.1.gemfile"
    - rvm: "2.1.8"
      gemfile: "gemfiles/rails-5.1.gemfile"

  allow_failures:
    - rvm: "2.4.0"
      gemfile: "gemfiles/rails-4.0.gemfile"
    - rvm: "2.4.0"
      gemfile: "gemfiles/rails-4.1.gemfile"

env:
  global: "RAILS_ENV=test"

before_install:
  - "gem update --system"
  - "gem update bundler"
before_script:
  - "bundle exec rake extension:install"

script: "bundle exec rake test"
